let but = document.querySelector("#\\:4\\.vw > div > div:nth-child(1) > div > div.yug4Pe > div > div.hZQfHc.a-E.PYtpaf > button")
alert(but.innerText)
but.click()
alert('hangout')
console.log('hangout')
